---
name: Checks

on: [push]

jobs:
  test-lints:
    name: Test and lints
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run:  docker-compose run --rm app sh -c "python manage.py test"
      - name: lints
        run:  docker-compose run --rm app sh -c "flake8"
